name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uses: anmol098/waka-readme-stats@V1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SHOW_COMMIT: "false"
          SHOW_DAYS_OF_WEEK: "false"
          SHOW_TIMEZONE: "true"
          TIME_RANGE: "false"
          SHOW_TOTAL: "false"  
          SHOW_LANGUAGES: "false"
          SHOW_LANGUAGE: "true"
          SHOW_EDITORS: "true"  
          SHOW_OS: "true"  
          SHOW_PROJECTS: "false"  
          SHOW_LINES_OF_CODE: "false"  
          SHOW_PROFILE_VIEWS: "false"  
          SHOW_SHORT_INFO: "false"
          SHOW_LOC_CHART: "false"
          COMMIT_MESSAGE: "📊 WakaTime Stats Update"
